# Site settings
title: 훌륭한 민주주의 앱
title_en: Awesome Democracy Apps
description: >
  바로 지금 이순간 전세계에서 더 나은 민주주의를 위한 다양한 노력들이 펼쳐지고 있습니다. 영감을 받거나 기여하거나 서로 더 이야기해보기 위해 훌륭한 민주주의 앱들을 소개합니다.
baseurl: '' # the subpath of your site, e.g. /blog/
url: '' # the base hostname & protocol for your site
permalink: pretty
timezone: Asia/Seoul

locale: ko

exclude: [ Gemfile, Gemfile.lock, README.md ]